services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:Mozihao08@db:5432/postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-ada-002}
      - CLASSIFIER_MODEL=${CLASSIFIER_MODEL:-gpt-4}
      - GENERATOR_MODEL=${GENERATOR_MODEL:-gpt-4}
      - VECTOR_DIM=1536
      - VECTOR_INDEX_PATH=/app/data/vector_index
      - DEBUG=True
    depends_on:
      - db
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
  
  db:
    build: 
      context: ./custom-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mozihao08
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/02-schema.sql

volumes:
  postgres_data:
