app = "intelligence-layer"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[env]
  PORT = "8000"
  EMBEDDING_MODEL = "text-embedding-3-small"
  CLASSIFIER_MODEL = "gpt-3.5-turbo"
  GENERATOR_MODEL = "gpt-3.5-turbo"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "intelligence_data"
  destination = "/data"
